### ISSUE TITLE
CRAN submission

### ISSUE THREAD

**Issue by parmsam** [ropensci/npi#27]
Thank you @frankfarach for adding the contribution guide. I noticed the package is not on CRAN. It looks like the npi package name is [available](https://cran.r-project.org/web/packages/available_packages_by_name.html#available-packages-N). Is there anything I can do to help get the package on CRAN? 

Helpful links included below.
* https://r-pkgs.org/release.html
* https://kbroman.org/pkg_primer/pages/cran.html

**Comment by frankfarach** [comment]
Thanks @parmsam for submitting this and other issues -- and a pull request! I really appreciate the help.

My plan is to [submit to rOpenSci first](https://github.com/frankfarach/npi/milestone/3) and [then CRAN](https://github.com/frankfarach/npi/milestone/2). I'll treat the present issue as the final step for submission to CRAN and have associated with that milestone. The intro vignette you submitted (#29) helps with both milestones.

Thanks again!

**Comment by frankfarach** [comment]
Submitted to CRAN
