### ISSUE TITLE
Using Organizational name in search return null

### ISSUE THREAD

**Issue by aakbarie** [ropensci/npi#79]
I am trying to search by organization name and zip code but unfortunately, it returns an empty list

`NPI_data = list(npi_search(organization_name = "PINN", postal_code = "95023"))`

**Comment by frankfarach** [comment]
When `npi_search()` returns an empty list, it means no records in the NPI Registry exactly matched the query parameters provided. To see partial matches, use the wildcard character (*). For example, the following query returns two records:

``` r
npi::npi_search(organization_name = "PINN*", postal_code = "95023")
#> 10 records requested
#> Requesting records 0-10...
#> # A tibble: 2 × 11
#>   npi     enume…¹ basic    other_…² identi…³ taxono…⁴ addres…⁵ practi…⁶ endpoi…⁷
#> * <chr>   <chr>   <list>   <list>   <list>   <list>   <list>   <list>   <list>  
#> 1 113441… Organi… <tibble> <tibble> <tibble> <tibble> <tibble> <tibble> <tibble>
#> 2 166955… Organi… <tibble> <tibble> <tibble> <tibble> <tibble> <tibble> <tibble>
#> # … with 2 more variables: created_date <dttm>, last_updated_date <dttm>, and
#> #   abbreviated variable names ¹​enumeration_type, ²​other_names, ³​identifiers,
#> #   ⁴​taxonomies, ⁵​addresses, ⁶​practice_locations, ⁷​endpoints
```
<sup>Created on 2023-10-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
